### ISSUE TITLE
How to change toolbar icon on iOS

### ISSUE THREAD

**Issue by khoatran121294** [PSPDFKit/react-native#136]
My customer asked me to replace the default toolbar icon but I cannot find any solutions to achieve that on iOS. Kindly guide me the way to update them quickly.
<img width="330" alt="screen shot 2018-10-23 at 10 52 37 am" src="https://user-images.githubusercontent.com/13750945/47332438-da033980-d6b1-11e8-8615-2c3309b171b7.png">

Thanks,
Khoa

**Comment by radazzouz** [comment]
Hi @khoatran121294,

The easiest way to accomplish this is to customize the toolbar in native code (Objective-C). We wrote about it in here: https://pspdfkit.com/blog/2018/how-to-extend-react-native-api/#customizing-the-ui-using-native-code

Here's how to customize the toolbar on iOS: https://pspdfkit.com/guides/ios/current/customizing-the-interface/customizing-the-toolbar/ 

We also have a working example in in this repo which shows how to do this on https://github.com/PSPDFKit/react-native/tree/customize-the-toolbar-in-native-code

Thanks!

**Comment by khoatran121294** [comment]
Hi @radazzouz,

Thanks for you reply. After review with the team, your guide is a bit overkill for us, keep in mind that we’re just pure javascript developers.

Let me share more detail about our client’s need. They just want to replace the bookmark icon. Is there any way that we can replace the original icon, or update the existing URL of the old icon (with one 1 line of code)

We really appreciate your help in advance
Thanks,

**Comment by radazzouz** [comment]
Hello again @khoatran121294,

Unfortunately we do not expose such APIs to Javascript. The toolbar buttons are deeply integrated into our SDK and it is oftentimes a lot easier and faster to do it in Objective-C rather than exposing the APIs to JavaScript.

In your case, you can use a custom button item which uses a custom image and uses the bookmark button item's target and action.

In Objective-C it would look like this: 

```objc
UIImage *image = [[UIImage imageNamed:@"custom_bookmark.png"] imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal];
UIBarButtonItem *customButtonItem = [[UIBarButtonItem alloc] initWithImage:image style:UIBarButtonItemStylePlain target:view.pdfController.bookmarkButtonItem.target action:view.pdfController.bookmarkButtonItem.action];
```

You can add this code snippet in `RCTPSPDFKitViewManager.m` if you are using the UI component or in `RCTPSPDFKitViewManager.m` if you are using the Native Module.

I am attaching the modified versions of these classes so you can test them on your side.

[RCTPSPDFKitManager.m.txt](https://github.com/PSPDFKit/react-native/files/2550193/RCTPSPDFKitManager.m.txt)
[RCTPSPDFKitViewManager.m.txt](https://github.com/PSPDFKit/react-native/files/2550194/RCTPSPDFKitViewManager.m.txt)

I hope that this will help you create a custom button with a custom image.

Thank you!
