### ISSUE TITLE
Can not run on android

### ISSUE THREAD

**Issue by mamaz** [PSPDFKit/react-native#14]
Hi,

I have problem running in Android, after following the Android getting started tutorial, and this: https://pspdfkit.com/guides/android/current/getting-started/try-the-demo/#
it produces this error:

<img width="967" alt="error" src="https://user-images.githubusercontent.com/2121162/27115810-6542fa18-50f7-11e7-937e-f3afffc4b022.png">

My `app/build.gradle` is like this:

```
repositories {
    jcenter()
    // add your additional maven repos here.

    maven {
        url 'https://customers.pspdfkit.com/maven/'

        credentials {
            username 'pspdfkit'
            password 'TRIAL-SOME-CODE'
        }
    }
}

dependencies {
    compile 'com.pspdfkit:pspdfkit-demo:3.1.1'
    compile project(':react-native-pspdfkit')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
}
```

Can you guys help?

**Comment by juliangrosshauser** [comment]
Hi @mamaz,

The problem is that the production version of PSPDFKit (`'com.pspdfkit:pspdfkit:3.0.0'`) can't be found on maven with a demo key (starting with `TRIAL-`).
To quickly fix this you can open your `node_modules/react-native-pspdfkit/android/build.gradle` file and replace `'com.pspdfkit:pspdfkit:3.0.0'` with `'com.pspdfkit:pspdfkit-demo:3.0.0'`.
We're working on a better solution right now and keep you posted.

You should also remove the `compile 'com.pspdfkit:pspdfkit-demo:3.1.1'` line from your `build.gradle`.

**Comment by mamaz** [comment]
Cool, thanks @juliangrosshauser

**Comment by juliangrosshauser** [comment]
@mamaz,

Gradle will now download the right PSPDFKit version depending on the Maven password.

Thank you for reporting this! :tada:
