### ISSUE TITLE
Improve Git Tags and Versioning

### ISSUE THREAD

**Issue by leoek** [PSPDFKit/react-native#173]
I am currently trying to get an ios build working. However I ran into some issues because of the current versioning.

I ran into compatibility issues of the sdk and the react-native-wrapper before with windows: https://github.com/PSPDFKit/react-native/issues/150 For single platform development additional git tags solve the issue and the are helpful for multi platform development as well. (For example if a new version for a specific platform is tested.)

The currently latest release of the wrapper is [1.23.0](https://github.com/PSPDFKit/react-native/releases/tag/1.23.0) However the commit c2c2339b0a4ee038adcb0cc24fe0f23767e30ee2 (which was after 1.23.0) seems to be needed for successful builds on ios.

Only adding the branch with yarn (`yarn add github:PSPDFKIT/react-native`) does not guarantee to get a working version at the moment. Explicitly specifying the release 1.23.0 does not help either, because of needed hotfixes like c2c2339b0a4ee038adcb0cc24fe0f23767e30ee2. Please add hotfix versions in these cases (in this case a 1.23.1) and also update the package.json with that version. This helps to avoid issues with yarn resolving an old or incorrect version. Also this enables apps which depend on react-native-pspdfkit to track the resolved version in their package.json and yarn.lock

```
"react-native-pspdfkit@github:PSPDFKIT/react-native":
  version "1.23.0"
  resolved "https://codeload.github.com/PSPDFKIT/reactnative/tar.gz/1d25e98ce132d48cf9eca330d6869cb5b4916455"
```

Currently only the resolved link would change. With specific version the locked version would change as well.

**Comment by radazzouz** [comment]
Hi @leoek,

Thanks for the detailed report!

> The currently latest release of the wrapper is 1.23.0 However the commit c2c2339 (which was after 1.23.0) seems to be needed for successful builds on ios.

Did you mean a different commit? I'm asking this because the commit that you mentioned (https://github.com/PSPDFKit/react-native/commit/c2c2339b0a4ee038adcb0cc24fe0f23767e30ee2) is a README update and not a hot fix. The `1.23.0` tag should have worked on iOS even without that commit. If that commit was required, then we should've definitely created a newer tag. We just created the `1.23.1` tag from which both iOS and Android should work.

Here's how we tag releases for our React Native wrapper:

- **Android and iOS:** Since a lot of users use both Android and iOS within the same project, we will keep a single tag for both platforms. We will continue increment the `1.23.x` tag.
- **Windows:** will have its own separate tag, in which we will mention the version of PSPDFKit. For example, `windows-1.11.0`

I am marking this issue as solved, but please do not hesitate to reach back to us should you have any further questions.

Once again, thank you!

**Comment by leoek** [comment]
@radazzouz 

Just noticed that you just created a git tag. Please update the version in the package.json as well. Currently I am using a fork to avoid resolving issues: https://github.com/leoek/react-native-pspdfkit/releases

You can see that I created multiple 1.23.x versions because different commits in master had different bugfixes/new features (for windows) while the version remained 1.23.0

**Comment by radazzouz** [comment]
Thank you, @leoek! A new release (1.23.2) is planned right after #192 is merged.
