### ISSUE TITLE
[UWP] Follow Up on css colors.

### ISSUE THREAD

**Issue by leoek** [PSPDFKit/react-native#215]
# Details

Hi I tested the new css colors. Overall it works pretty good 👍 but there are still some minor things which should be adressed:

1. If I hover over the buttons in the toolbar, there is a mouseover effect which does not use the supplied color. Also for the selections the default color is used. This looks a bit weird.

![2019-04-18](https://user-images.githubusercontent.com/9424038/56360959-6cf6d980-61e6-11e9-875e-b7da34505bc9.png)

2. If the there is a key in the style array for one of the colors, but there is no color (`undefined` / `null`) the app crashes.

# Acceptance Criteria

- [ ] App does not crash if an invalid color is supplied (for example `highlightColor: null`)
- [ ] These colors are used for effects as well (for example mouseover)

**Comment by leoek** [comment]
windows sdk: 1.12
wrapper: 1.23.7

**Comment by leoek** [comment]
@nickwinder Got some new issues with the colors. If any color is supplied in a production build, the app crashes if the viewer is opened.

**Comment by nickwinder** [comment]
@leoek 
Sorry for the delay.
1. From the example, you've given it seems that `highlightColor` is missing or not used? You can see the catalog example using this color https://github.com/PSPDFKit/react-native/blob/44598d114a2f0ede56f5a4d1dc4e316b0f3dac42/samples/Catalog/Catalog.windows.js#L189 which works in the correct fashion. 
The selections in the dropdown menus are not currently supported so I will open an internal support request for this. 

2. Fixed in https://github.com/PSPDFKit/react-native/pull/218

I was able to reproduce the CSS Color issue in production mode, therefore, I opened a new issue for this. https://github.com/PSPDFKit/react-native/issues/219
