### ISSUE TITLE
Question: integrating with react-native project.

### ISSUE THREAD

**Issue by maheshgajadhar** [PSPDFKit/react-native#230]
Hi,

I am following the installing guide, step 7 is not clear for me, can someone tell me how to do this? I dont know where i can find these frameworks.

**Create the folder ios/PSPDFKit and copy PSPDFKit.framework and PSPDFKitUI.framework into it.**

**Comment by radazzouz** [comment]
Hi @maheshgajadhar,

Or React Native wrapper requires the native frameworks. In order to download PSPDFKit.framework and PSPDFKitUI.framework you need to signup for a free trial here: https://pspdfkit.com/try/.

See the following in the README:

> This wrapper requires a valid license of PSPDFKit. Licenses are per platform. You can request [a trial license here](https://pspdfkit.com/try/).

I am closing this issue, but please do not hesitate to reach out to us in https://support.pspdfkit.com/hc/en-us/requests/new should you have any further questions.

Thank you!
