### ISSUE TITLE
 Code signing framework "PSPDFKit.framework" failed

### ISSUE THREAD

**Issue by Andrea-Arguello** [PSPDFKit/react-native#288]
# Details
- Using tag 1.24.0
- Following the CocoaPods installation guide(https://github.com/PSPDFKit/react-native/blob/accdd0b5d4f8d0aa11d4caa69c29e31dd5e7a3de/ios/cocoapods.md) 
EDIT
- Project ejected to Expo Kit (hence running React Native 0.59.8)
## Tried
-  Using PSPDFKit version 8.5.1
-  Using PSPDFKit version 8.2.3

# Error
- Code signing framework "PSPDFKit.framework" failed
- Distribution logs (IDEDistributionPipeline.log) show 

```
2019-08-28 18:23:17 +0000  /var/folders/9c/lqnw_k5n4r75w6c0njt12_hc0000gp/T/XcodeDistPipeline.~~~neMuTc/Root/Payload/exeboard.app/Frameworks/PSPDFKit.framework: code object is not signed at all
2019-08-28 18:23:17 +0000  /usr/bin/codesign exited with 1
```

**Comment by steipete** [comment]
What Xcode version are you using? Also check with `xcode-select -p`

**Comment by Andrea-Arguello** [comment]
We are using Xcode 10.3. The app builds and runs normally on an emulator, it is when trying to distribute to the iOS Store that it fails.

**Comment by radazzouz** [comment]
Also, which version of React Native are you using?

The CocoaPods integration from https://github.com/PSPDFKit/react-native/blob/accdd0b5d4f8d0aa11d4caa69c29e31dd5e7a3de/ios/cocoapods.md has completely changed in React Native 0.60.x. 

If you're using React Native 0.60.x, please switch to the default integration steps from https://github.com/PSPDFKit/react-native#getting-started which uses CocoaPods. 

Otherwise, if you absolutely must use an older tag, consider using the manual integration steps from https://github.com/PSPDFKit/react-native/tree/accdd0b5d4f8d0aa11d4caa69c29e31dd5e7a3de#getting-started

Let us know if this helps you.

**Comment by Andrea-Arguello** [comment]
I am using RN 0.59.8, as the project was ejected to Expo Kit. We've used the CocoaPods integration described here: https://github.com/PSPDFKit/react-native/blob/accdd0b5d4f8d0aa11d4caa69c29e31dd5e7a3de/ios/cocoapods.md

**Comment by radazzouz** [comment]
I suspect that this is caused by adding the frameworks again in steps 16-18 from the [old and deprecated integration steps](https://github.com/PSPDFKit/react-native/blob/accdd0b5d4f8d0aa11d4caa69c29e31dd5e7a3de/ios/cocoapods.md), where the frameworks are added again. It's hard to pinpoint the exact cause of this issue with the information that we have at hand.

Please try switching to the manual integration steps from https://github.com/PSPDFKit/react-native/tree/accdd0b5d4f8d0aa11d4caa69c29e31dd5e7a3de#getting-started and let us know if you're still getting the code signing error.

**Comment by Andrea-Arguello** [comment]
"react-native link" did not add the .a file to the workspace, we manually copied the RCTPSPDFKit.xcodeproj from the node_modules. This threw errors regarding React/RCTConvert.h and React/RCTBridgeModule.h in the imports ("file not found").

**Comment by radazzouz** [comment]
Did you sort it out? If not, then take a look at:

> 11. Link with the libRCTPSPDFKit.a static library (if libRCTPSPDFKit.a is already there but greyed out, delete it and link it again): 

from https://github.com/PSPDFKit/react-native/tree/accdd0b5d4f8d0aa11d4caa69c29e31dd5e7a3de#getting-started

Does this help?

**Comment by Andrea-Arguello** [comment]
After doing ```react-native link react-native-pspdfkit```, the libRCTPSPDFKit.a file does not show up in the workspace. We tried adding it manually, copying it from the node_modules/react-native-pspdfkit/ios folder.

**Comment by radazzouz** [comment]
I see... Thanks for the additional details. Did that work? Did it fix the code signing issue?

**Comment by Andrea-Arguello** [comment]
I cannot test if it has fixed the code signing, as the project doesn't build because of the aforementioned errors.

**Comment by Andrea-Arguello** [comment]
[I have created a project so that someone can replicate this issue.](https://github.com/Andrea-Arguello/pspdfmario) It contains an empty project ejected from expo. Locally, the next step should be 11 as described [here](https://github.com/PSPDFKit/react-native/tree/accdd0b5d4f8d0aa11d4caa69c29e31dd5e7a3de/), but in previous runs, the libRCTPSPDFKit.a static library is nowhere to be seen on the workspace. This is our main issue, since copying it from the node_modules into the workspace leads to more issues.

**Comment by radazzouz** [comment]
Thanks for sending us the sample project, @Andrea-Arguello!

There's no need to perform step 11 of the old integration steps. That's because all of your dependencies, including our PSPDFKit wrapper, are handled by CocoaPods.

Notice that the only dependency that your project uses is `libPods-Mario.a`. There's no other React Native specific dependency.

<img width="691" alt="Screen Shot 2019-08-31 at 9 53 06 AM" src="https://user-images.githubusercontent.com/7443038/64065696-96853000-cbde-11e9-8008-9778afbb7d41.png">

In other words, your project still uses CocoaPods and not the manual integration steps, so you can't manually integrate the native frameworks. You will need to go full in on integrating with CocoaPods.

That said, I noticed that in your Podfile you are only adding the our React Native wrapper (`react-native-pspdfkit`) and not the native SDKs and when you attempt to build you will get an error that our wrapper can't find the PSPDFKit module.

So I modified your Podfile like so:

```diff
source 'https://github.com/CocoaPods/Specs.git'
- platform :ios, '10.0'
+ platform :ios, '11.0'

[...]

pod 'react-native-pspdfkit', :path => '../node_modules/react-native-pspdfkit'
+ pod 'PSPDFKit', podspec: 'https://customers.pspdfkit.com/cocoapods/YOUR_COCOAPODS_KEY_GOES_HERE/pspdfkit/latest.podspec'
post_install do |installer|
    installer.pods_project.main_group.tab_width = '2';
    installer.pods_project.main_group.indent_width = '2';

    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|

     [...]

+      # Update the `FRAMEWORK_SEARCH_PATHS` so that the PSPDFKit wrapper can link the native frameworks.
+      if pod_name.start_with?('react-native-pspdfkit')
+        target_installation_result.native_target.build_configurations.each do |config|
+          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
+          config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= ['$(PODS_ROOT)/PSPDFKit/']
+        end
      end

      [...]

  end
end
```

I am also attaching it here: [Podfile.txt](https://github.com/PSPDFKit/react-native/files/3562572/Podfile.txt)

In my tests things worked great, let me know if this fixes the integration in your project.

Have a great weekend!

**Comment by Andrea-Arguello** [comment]
@radazzouz solution worked. Closing this issue.
