### ISSUE TITLE
[Android/iOS] Question: Can we configure the colour picker for annotations?

### ISSUE THREAD

**Issue by naoey** [PSPDFKit/react-native#301]
Does the library support configuring what colour options are given in the colour palette and which is the default colour? I found that the iOS SDK [supports setting the last used colour](https://pspdfkit.com/guides/ios/current/annotations/changing-default-values-for-color-and-text-size-of-annotations/), but I wasn't able to find an equivalent for Android. We have a requirement where we need to change the default colour and colour options for annotations in our app based on the user.

I'm also unclear whether this can be achieved through the initial configuration object? On looking through the docs for configuration nothing particularly mentions the colour picker.

Even if the SDKs do support it, I don't believe the React Native library has any bindings to invoke this functionality at present?

I'd be happy to integrate the React Native side of it myself if I could get clarification on whether this capability exists in the native SDKs!

**Comment by radazzouz** [comment]
Hi @naoey,

I will address the iOS part of your question below. Someone from the Android team will followup in here shortly.

The iOS guide that you mentioned allows you to configure the default values for the color and the text size.

If you're looking to configure the available colors in the Annotation Inspector, please take a look at the following guides:

- https://pspdfkit.com/guides/ios/current/annotations/annotation-inspector/
- https://pspdfkit.com/guides/ios/current/knowledge-base/how-do-i-customize-the-annotation-inspector/
- https://pspdfkit.com/guides/ios/current/annotations/customizing-presets/

Please also refer to the examples from [PSPDFCatalog](https://pspdfkit.com/guides/ios/current/getting-started/example-projects/#pspdfcatalog) that are mentioned in the aforementioned guides.

Note that none of these APIs are bridged to React Native. We wrote about how to Customize the UI Using Native Code in our blog here: https://pspdfkit.com/blog/2018/how-to-extend-react-native-api/#customizing-the-ui-using-native-code. We also modified the Catalog (our sample project) in the [customize-the-toolbar-in-native-code branch](https://github.com/PSPDFKit/react-native/tree/customize-the-toolbar-in-native-code) to illustrate how such scenarios can be achieved.

Let me know if this helps you with your use case.

**Comment by irgendeinich** [comment]
On Android we have similar API as on iOS that allows you to configure which colors are available in the inspector, you can find the guide for that [here](https://pspdfkit.com/guides/android/current/annotations/annotation-configuration/). There is also the `AnnotationConfigurationExampleActivity` example in our catalog app showing the usage of this API. 

Just like on iOS these APIs are not bridged to react-native, so you'll have to provide your own native code to handle this. Since you need access to the `PdfFragment` you'll probably want to fork the wrapper and add the code directly to the [`PdfFragment`](https://github.com/PSPDFKit/react-native/blob/master/android/src/main/java/com/pspdfkit/views/PdfView.java#L295).

**Comment by naoey** [comment]
That seems like what I was looking for. I'll give it a shot over the next couple of days and get back if I have any further questions. Thanks!

**Comment by radazzouz** [comment]
Awesome! Glad we could help. I am closing this ticket a resolved.
