### ISSUE TITLE
Replicating getAllAnnotations for PSPDFKit.present

### ISSUE THREAD

**Issue by Andrea-Arguello** [PSPDFKit/react-native#304]
# Details
From #293, it seems like the getAllAnnotations method can only be invoked if using the PSPDFKit UI Component, instead of the .present with the NativeModules. Can this be reproduced for the latter case?

## Additional information
I am currently working with the release 1.24.0.

**Comment by radazzouz** [comment]
Hi @Andrea-Arguello,

All of the [annotation manipulation functions](https://github.com/PSPDFKit/react-native/blob/a32aebfc70d6873d7eaa4de303cc731cf48d4d6d/index.js#L150), including `getAllAnnotations` are implemented, for the UI component and not the native module. This is by design: the native module was designed to only present a [`PSPDFViewController`](https://pspdfkit.com/api/ios/Classes/PSPDFViewController.html) modally, for advanced projects most of our customers use the UI component. 

If your project requires advanced annotation manipulations, I would recommend using the UI component instead. Is there anything preventing you from using to the UI component?

Have a great weekend!
