### ISSUE TITLE
[Android] UI Component doesn't render anything (Tag 1.24.4)

### ISSUE THREAD

**Issue by Andrea-Arguello** [PSPDFKit/react-native#317]
The UI component for Android is not rendering the pdf. I saw that this was fixed in a later tag but, since my project uses expo and therefore, RN 0.58, I cannot pull said tag.

Here is a repo with the issue mentioned, currently using tag 1.24.0: https://github.com/cluis13915/pspdfkit-1-24-0-android-issue

Note that this is a public repo that was created with a trial key, that has already expired.

**Comment by Andrea-Arguello** [comment]
I have updated to tag 1.24.4, but the issue has not been solved yet

**Comment by irgendeinich** [comment]
Hey
I had a quick look at you example repo.

```
<PSPDFKitView
            ref="pdfView"
            document={document}
            configuration={CONFIGURATION}
            style={{ flex:1, color: '#1EADD1' }}
            showCloseButton={true}
            onCloseButtonPressed={this.onClosePDFViewer}
          />
```

It looks like you are missing the `fragmentTag` prop in there. Could you try adding that and reporting if it starts working.

**Comment by Andrea-Arguello** [comment]
That has solved the issue. Thanks.
Now, I'm having the trouble described on #245. Has a solution been provided for this yet? If anything, I'd like to just have the annotation and search buttons.

**Comment by Andrea-Arguello** [comment]
May I also ask, why is this "fragmentTag" not needed for iOS? I was able to render the toolbar there without said attribute. Will this cause issues in the future?

**Comment by irgendeinich** [comment]
Great to hear that is it working, I'm gonna close this issue in that case.

To answer why we need a `fragmentTag` on Android. This is because internally we use a `Fragment` that is attached to the `Activity` in order to uniquely identify multiple `PSPDFKitView` in a single screen we need to set a separate `fragmentTag` on each of them. This will not cause issues on iOS as the property is simply ignored there.

I'll answer in #245 separately.
