### ISSUE TITLE
linking not working on windows 10

### ISSUE THREAD

**Issue by MarceloEmmerich** [PSPDFKit/react-native#62]
everything works until I try:

`react-native link react-native-pspdfkit`

this yields 

```
Scanning folders for symlinks in <node_module path here> (111ms)
rnpm-install info Android module react-native-pspdfkit is already linked
rnpm-install info iOS module react-native-pspdfkit is already linked
rnpm-install ERR! Something went wrong while linking. Error: ENOENT: no such file or directory, open 'C:\projects\myapp\myapp\windows\myapp\MainPage.cs'
Please file an issue here: https://github.com/facebook/react-native/issues

ENOENT: no such file or directory, open 'C:\projects\myapp\myapp\windows\myapp\MainPage.cs'
```
versions:

```
    "react": "16.2.0",
    "react-native": "0.52.0",
    "react-native-windows": "^0.52.0-rc.3"
```

**Comment by radazzouz** [comment]
Thanks for reporting @MarceloEmmerich!

We're investigating and we'll follow up in here shortly.

**Comment by nickwinder** [comment]
Hi @MarceloEmmerich,

This issue comes about when linking is run after the windows project has been created. Preferably you should run `react-native link react-native-pspdfkit` prior to `react-native windows` which creates the windows project. Sadly the windows react native project still has not implemented the automated linking procedure, so it has to be manually added. https://github.com/Microsoft/react-native-windows/blob/master/docs/LinkingLibrariesWindows.md

You can safely ignore this error and carry on by linking the module manually. To make things easy this is described here https://github.com/PSPDFKit/react-native#getting-started-2 from step 10 onwards. Just follow this and you will be up and running.

**Comment by radazzouz** [comment]
Thanks, @nickwinder!

@MarceloEmmerich, I'll go ahead and close this issue, but please feel free to follow up in here anything is unclear.

**Comment by MarceloEmmerich** [comment]
Thanks, I got it working now.
