### ISSUE TITLE
present() API call for windows?

### ISSUE THREAD

**Issue by MarceloEmmerich** [PSPDFKit/react-native#64]
can we directly load a PDF in on windows 10 using the present() API like in iOS and Android?

**Comment by pweiskircher** [comment]
Unfortunately, a Windows 10 UWP app only has very restrictive access to the file system, see here: https://docs.microsoft.com/en-us/windows/uwp/files/file-access-permissions

Due to this, we decided that for now offering the same `present()` API on Windows wouldn't make a lot of sense, as it might lead to confusion on why it can't just open any file, like on iOS or Android.

Right now, you can only call `OpenFile` to display a dialog to the user. But I completely understand that this is very limiting. But this should be relatively easy to extend, if you need this functionality right now. As you can see in the above link, you can create a `StorageFile` using, for example, `StorageFile.GetFileFromApplicationUriAsync`. 

You could add a `presentFromApplicationDirectory` method in https://github.com/PSPDFKit/react-native/blob/master/windows/ReactNativePSPDFKit/ReactNativePSPDFKit/PSPDFKitModule.cs that first resolves the `StorageFile` using the method mentioned above and then calls `LoadViaAPI` in the same class.

**Comment by steipete** [comment]
Thanks for the suggestion! 
This does make sense for us to add as well. We wanted to get the React Native for Windows UWP wrapper out there on day one, and we certainly understand that we can make this even better.

**Comment by MarceloEmmerich** [comment]
Sounds good. Thanks for the suggestion!

**Comment by nickwinder** [comment]
`Present` is now supported with the use of https://github.com/itinance/react-native-fs as seen in the catalog example https://github.com/PSPDFKit/react-native/blob/a54a279e1c67c10a772a45f73d221d033a45326a/samples/Catalog/Catalog.windows.js#L65-L69

Please note, this will still not work with standard file paths to any location and ensure that you follow the permission rules in docs.microsoft.com/en-us/windows/uwp/files/file-access-permissions.
